### PR TITLE
META: Add action to build docs on Netlify

### PR DESCRIPTION
**Pull request by unclecheese**

### CODE REVIEW

**Comment by unclecheese** [comment]
Please write to `aaron@silverstripe.com` to obtain the dependent secret.

**Comment by emteknetnz** [comment]
@unclecheese is this ready to be merged as is?

**Comment by emteknetnz** [comment]
Related PR:
https://github.com/symbiote/silverstripe-versionedfiles/pull/66

**Comment by brynwhyman** [comment]
Hey @nglasl pinging you here as well :) 

This is similar to: https://github.com/symbiote/silverstripe-advancedworkflow/pull/415#issuecomment-651429292, currently blocking module docs from appearing in the [Silverstripe docs site](https://docs.silverstripe.org/en/4/).

**Review by nglasl — APPROVED** [review]

**Comment by nglasl** [comment]
This one should be sorted now too.

**Pull request merged**
